Vagrant.configure("2") do |config|
  config.vm.box = "debian/bookworm64"
  config.vm.box_check_update = false

  hosts = {
    "cyril"   => "192.168.121.10",
    "walid"   => "192.168.121.11",
    "ultrac1" => "192.168.121.12",
    "ultrac2" => "192.168.121.13"
  }

  hosts.each do |name, ip|
    config.vm.define name do |vm|
      vm.vm.hostname = name
      vm.vm.network "private_network", ip: ip, libvirt__network_name: "vagrant-libvirt", type: "static"

      vm.vm.provider :libvirt do |libvirt|
        libvirt.memory = 2048
        libvirt.cpus = 2
      end

      vm.vm.provision "shell", inline: <<-SHELL
        apt update
        apt install -y openssh-server sudo
        systemctl enable ssh
        systemctl start ssh
        echo "# ---Fellow Vagrant provisionned hosts---" >> /etc/hosts
      SHELL

      hosts.each do |other_name, other_ip|
        next if name == other_name
        vm.vm.provision "shell", inline: "echo '#{other_ip} #{other_name}' >> /etc/hosts"
      end
      # Ansible and ansible user on Cyril
      if name == "cyril"
        vm.vm.provision "shell", inline: <<-SHELL
          apt-get install -y ansible
          useradd -m -s /bin/bash ansible
          echo "ansible ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/ansible
          chmod 0440 /etc/sudoers.d/ansible
        SHELL
      end
      # management user on each other vm
      if ["ultrac1", "ultrac2", "walid"].include?(name)
        vm.vm.provision "shell", inline: <<-SHELL
          useradd -m -s /bin/bash management
          echo "management ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/management
          chmod 0440 /etc/sudoers.d/management
        SHELL
      end
    end
  end
end
