- name: Join as worker
  shell: docker swarm join --token {{ hostvars['walid'].swarm_worker_token }} {{ hostvars['walid'].swarm_manager_ip }}:2377
  register: join_result
  failed_when: "'already part of a swarm' not in join_output.stderr and join_output.rc != 0"

