---
- name: GFS Cluster ansible setup - \#ULTRACYRIL
  hosts: glusterfs
  become: true
  roles:
    - glusterfs

- name: Docker Swarm setup
  hosts: swarm_nodes
  become: true
  roles:
    - docker_swarm

- name: Deploy Portainer on walid
  hosts: swarm_manager
  become: true
  roles:
    - portainer

