- name: Ensure python3-docker is installed (OS package)
  ansible.builtin.apt:
    name: python3-docker
    state: present
    update_cache: yes
  become: true

- name: Deploy Portainer service on manager node
  docker_swarm_service:
    name: "{{ portainer_service_name }}"
    image: "{{ portainer_image }}"
    publish:
      - target_port: 9000
        published_port: "{{ portainer_port }}"
        protocol: tcp
        mode: ingress
    mounts:
      - type: volume
        source: "{{ portainer_volume_name }}"
        target: /data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    mode: replicated
    replicas: 1
    restart_config:
      condition: any
